site_name: Notes
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: black
      accent: white 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: black
      accent: white

plugins:
  - mkdocstrings

nav:
  - Home: index.md 
  - Artificial Intelligence: artificial_intelligence/index.md
  - Languages: languages/index.md
  - Database and Data Warehouse: database_datawarehouse/index.md
  - Container: container/index.md
  - Version Control Systems: version_control/index.md
  - Projects: projects/index.md
  - API: api/index.md
  - Operating Systems: operating_systems/index.md
  - Cloud Technologies: cloud_technologies/index.md

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ronakr14

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      
copyright: |
  &copy; 2024 <a href="https://github.com/ronakr14"  target="_blank" rel="noopener">Ronak Rathore</a>